---
- hosts: all
  become: true
  tasks:
  - name: Add repo-key to the host
    shell: sudo curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
  - name: Adding apt repository for InfluxDB
    apt_repository:
      repo: deb https://repos.influxdata.com/ubuntu bionic stable
      state: present
      filename: influxdb.list
  - name: Install InfluxDB binaries
    apt: 
      name: influxdb
      state: present
      update_cache: yes
  - name: Copy the influxdb.conf command to server location
    copy: 
      src: influxDB/influxdb.conf 
      dest: /etc/influxdb/influxdb.conf
      owner: root
      group: root
      mode: 0777
  - name: Restart InfluxDB
    service:
      name: influxdb
      daemon_reload: yes
      enabled: yes
      state: restarted
  - name: Create the admin account of the influxDB
    shell: curl -XPOST "http://localhost:8086/query" --data-urlencode "q=CREATE USER superadmin WITH PASSWORD 'vagrant1234' WITH ALL PRIVILEGES"
#
# adding telegraf to the influxDB-node to export basic metrics
#
  - name: Install telegraf 
    shell: |
      wget -qO- https://repos.influxdata.com/influxdb.key | sudo apt-key add - ;
      source /etc/lsb-release ;
      echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
  - name: Install telegraf binaries
    apt: 
      name: telegraf
      state: present
      update_cache: yes
  - name: Copy the telegraf.conf command to server location
    copy: 
      src: telegraf/telegraf.conf 
      dest: /etc/telegraf/telegraf.conf
      owner: root
      group: root
      mode: 0777
  - name: Restart telegraf
    service:
      name: telegraf
      daemon_reload: yes
      enabled: yes
      state: restarted