mcc: "208"                 
mnc: "95"                   
eutraBand: "7"             
downlinkFrequency: "2685000000L"    
uplinkFrequencyOffset: "-120000000"
configurationPathofCN: "/var/snap/oai-cn/current/"
configurationPathofRAN: "/var/snap/oai-ran/current/"
snapBinaryPath: "/snap/bin/"
mmeDomainName: "oaicn"
dns: "172.24.2.4"
flexRAN: true
flexRANDomainName: "flexran"
test: false
